version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  spring:
    build: .
    volumes:
      - .:/app
    command: spring server
    # This ensures that the pid namespace is shared between the host
    # and the container. It's not necessary to be able to run spring
    # commands, but it is necessary for "spring status" and "spring stop"
    # to work properly.
    pid: host
  web:
    build: .
    command: bundle exec rails s -p 1337 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "1337:1337"
    depends_on:
      - db
      - spring
